name: 'Issue 1742: annotation example'
description: Test annotations
runs:
  using: "composite"
  steps:
    - run: echo Hello there once!
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::error file=test_file.txt,line=1,col=1,endColumn=3::Testing error 1"
      shell: bash
