name: 'Issue 1742: annotation example'
description: Test annotations
runs:
  using: "composite"
  steps:
    - run: echo Hello there once!
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::error::Testing error 1"
      shell: bash
    - run: echo Hello there
      shell: bash
    - name: Testing the Error Workflow Command
      run: echo "::error::Testing error 2"
      shell: bash
    - name: Testing the Warning Workflow Command
      run: echo "::warning::Testing warning"
      shell: bash
    - name: Testing the Notice Workflow Command
      run: echo "::notice::Testing notice"
      shell: bash
